<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>lab2</title>

  <link rel="stylesheet" href="./view/css/films.css">
</head>
<body>
  <header>
    <div class="container">
      <div class="goToModPicker">
        <p>Pick mod</p>
      </div>
      <div class="daysFilter">
        <form action="index.php" method="post">
          <label class="filterText">Дней после релиза</label>
          <select name="days">
            <option value="7">7</option>
            <option value="14">14</option>
            <option value="21">21</option>
            <option value="28">28</option>
          </select>
          <input type="submit" name="applyDays" value="Apply">
        </form>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="list">
      <?php
        $i=0;
        foreach ($data as $film) {
          $datetime1 = date_create();
          $datetime2 = date_create($film->releaseDate);
          $interval = date_diff($datetime1, $datetime2);

          if ($interval->m === 0 && $interval->d <= $dayFilter) {
            $i++;
      ?>
      <div class="filmCard">
        <h2><?php echo $film->title ?></h2>
        <h3>(<?php echo $film->titleOriginal ?>)</h3>
        <img src="<?php echo $film->poster ?>" alt="">
        <p><?php echo $film->overview ?></p>
        <h3 class="genre">Жанры:</h3>
        <p><i><?php echo $film->genres ?></i></p>
        <p class="date">Дата релиза: <?php echo $film->releaseDate ?></p>
      </div>
      <?php
          }
        }
        if ($i === 0) {
      ?>
          <p class="warning">Нет фильмов удовлеторяющих условию. Попробуйте изменить количество дней с момента релиза или запустить Query mod.</p>
      <?php
        }
      ?>
    </div>
  </div>
  <script>
    document.querySelector('.goToModPicker').addEventListener('click',function(){
      document.location.href = "pickMod.php";
    });
  </script>
</body>
</html>
